src/Entity/Idea.php
<?php

namespace App\Entity;

use App\Repository\IdeaRepository;
use DateTime;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=IdeaRepository::class)
 */
class Idea
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;
    /**
     * @ORM\Column(type="string", length=63)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=127)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=8191 , nullable=true)
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="ideas")
     * @ORM\JoinColumn(nullable=false)
     */
    private $owner;

    /**
     * @ORM\Column(type="datetime")
     */
    private $published_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $last_update_at;

    /**
     * @ORM\ManyToMany(targetEntity=Tag::class, inversedBy="ideas", cascade={"persist"})
     * @Assert\Count(
     *     max = "4",
     *     maxMessage="Máximo de 4 tags"
     * )
     */
    private $tags;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="idea", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity=Like::class, mappedBy="idea", orphanRemoval=true)
     */
    private $likes;

    /**
     * @ORM\ManyToMany(targetEntity=Sector::class, mappedBy="ideas")
     * @Assert\Count(
     *     max = "3",
     *     maxMessage="Máximo de 3 sectores"
     * )
     */
    private $sectors;

    /**
     * @ORM\Column(type="boolean")
     */
    private $anonymous;

    /**
     * @ORM\ManyToOne(targetEntity=IdeaStatus::class, inversedBy="ideas")
     * @ORM\JoinColumn(nullable=false)
     */
    private $status;

    /**
     * @ORM\OneToMany(targetEntity=File::class, mappedBy="idea", orphanRemoval=true)
     */
    private $files;

    /**
     * @ORM\OneToMany(targetEntity=Note::class, mappedBy="idea", orphanRemoval=true)
     */
    private $notes;

    /**
     * @ORM\Column(type="datetime")
     */
    private $last_status_change;


    public function __construct()
    {
        $this->tags = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->likes = new ArrayCollection();
        $this->sectors = new ArrayCollection();
        $this->published_at = new DateTime();
        $this->last_update_at = new DateTime();
        $this->anonymous=false;
        $this->files = new ArrayCollection();
        $this->notes = new ArrayCollection();
        $this->last_status_change = new DateTime();
        $this->status = null;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getOwner(): ?User
    {
        return $this->owner;
    }

    public function setOwner(?User $owner): self
    {
        $this->owner = $owner;
        return $this;
    }

    public function getPublishedAt(): ?DateTimeInterface
    {
        return $this->published_at;
    }

    public function setPublishedAt($published_at): self
    {
        $this->published_at = $published_at;
        return $this;
    }

    public function getLastUpdateAt(): ?DateTimeInterface
    {
        return $this->last_update_at;
    }

    public function setLastUpdateAt($last_update_at): self
    {
        $this->last_update_at = $last_update_at;
        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setIdea($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getIdea() === $this) {
                $comment->setIdea(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return (string) $this->getName();
    }

    /**
     * @return Collection|Like[]
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(Like $like): self
    {
        if (!$this->likes->contains($like)) {
            $this->likes[] = $like;
            $like->setIdea($this);
        }

        return $this;
    }

    public function removeLike(Like $like): self
    {
        if ($this->likes->removeElement($like)) {
            // set the owning side to null (unless already changed)
            if ($like->getIdea() === $this) {
                $like->setIdea(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Sector[]
     */
    public function getSectors(): Collection
    {
        return $this->sectors;
    }

    public function addSector(Sector $sector): self
    {
        if (!$this->sectors->contains($sector)) {
            $this->sectors[] = $sector;
            $sector->addIdea($this);
        }

        return $this;
    }

    public function removeSector(Sector $sector): self
    {
        if ($this->sectors->removeElement($sector)) {
            $sector->removeIdea($this);
        }

        return $this;
    }


    public function getAnonymous(): ?bool
    {
        return $this->anonymous;
    }

    public function setAnonymous(bool $anonymous): self
    {
        $this->anonymous = $anonymous;

        return $this;
    }

    public function getStatus(): ?IdeaStatus
    {
        return $this->status;
    }

    public function setStatus(?IdeaStatus $status): self
    {
        if ($this->getStatus() !== $status) {
            $this->setLastStatusChange(new DateTime());
        }
        $this->status = $status;
        return $this;
    }

    /**
     * @return Collection|File[]
     */
    public function getFiles(): Collection
    {
        return $this->files;
    }

    public function addFile(File $file): self
    {
        if (!$this->files->contains($file)) {
            $this->files[] = $file;
            $file->setIdea($this);
        }

        return $this;
    }

    public function removeFile(File $file): self
    {
        if ($this->files->removeElement($file)) {
            // set the owning side to null (unless already changed)
            if ($file->getIdea() === $this) {
                $file->setIdea(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Note[]
     */
    public function getNotes(): Collection
    {
        return $this->notes;
    }

    public function addNote(Note $note): self
    {
        if (!$this->notes->contains($note)) {
            $this->notes[] = $note;
            $note->setIdea($this);
        }

        return $this;
    }

    public function removeNote(Note $note): self
    {
        if ($this->notes->removeElement($note)) {
            // set the owning side to null (unless already changed)
            if ($note->getIdea() === $this) {
                $note->setIdea(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        $this->tags->removeElement($tag);

        return $this;
    }

    public function getLastStatusChange(): ?\DateTimeInterface
    {
        return $this->last_status_change;
    }

    public function setLastStatusChange(\DateTimeInterface $last_status_change): self
    {
        $this->last_status_change = $last_status_change;

        return $this;
    }

}

src/Entity/IdeaStatus.php
<?php

namespace App\Entity;

use App\Repository\IdeaStatusRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=IdeaStatusRepository::class)
 */
class IdeaStatus
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=63, nullable=true)
     */
    private $name;

    /**
     * @ORM\OneToMany(targetEntity=Idea::class, mappedBy="status")
     */
    private $ideas;

    /**
     * @ORM\Column(type="integer")
     */
    private $number;

    /**
     * @ORM\Column(type="integer")
     */
    private $max_number;

    /**
     * @ORM\Column(type="string", length=31)
     */
    private $color;

    public function __construct()
    {
        $this->color="#0066ff";
        $this->max_number=5;
        $this->ideas = new ArrayCollection();
    }

    public function __toString(): string
    {
        return (string) $this->getName();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|Idea[]
     */
    public function getIdeas(): Collection
    {
        return $this->ideas;
    }

    public function addIdea(Idea $idea): self
    {
        if (!$this->ideas->contains($idea)) {
            $this->ideas[] = $idea;
            $idea->setStatus($this);
        }

        return $this;
    }

    public function removeIdea(Idea $idea): self
    {
        if ($this->ideas->removeElement($idea)) {
            // set the owning side to null (unless already changed)
            if ($idea->getStatus() === $this) {
                $idea->setStatus(null);
            }
        }

        return $this;
    }

    public function getNumber(): ?int
    {
        return $this->number;
    }

    public function setNumber(int $number): self
    {
        $this->number = $number;

        return $this;
    }

    public function getMaxNumber(): ?int
    {
        return $this->max_number;
    }

    public function setMaxNumber(int $max_number): self
    {
        $this->max_number = $max_number;

        return $this;
    }

    public function getColor(): ?string
    {
        return $this->color;
    }

    public function setColor(string $color): self
    {
        $this->color = $color;

        return $this;
    }
}

templates/components/error_and_success.html.twig
{% for message in app.flashes('error') %}
    <div class="alert alert-danger alert-dismissible fade show mt-1" role="alert">
        <strong>{{  message }}</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
{% endfor %}
{% for message in app.flashes('success') %}
    <div class="alert alert-success bg-success text-dark alert-dismissible fade show mt-1" role="alert">
        <strong>{{  message }}</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
{% endfor %}
{% for message in app.flashes('warning') %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>{{  message }}</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
{% endfor %}
{% for message in app.flashes('new_idea') %}
    <div class="alert alert-success bg-success text-dark alert-dismissible fade show mt-1" role="alert">
        <strong>{{  message }}</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
{% endfor %}

templates/components/ideas_list.html.twig
<table class="table {{ class_table|default('') }} widget">
    <thead>
    <tr>
        <th>Nombre</th>
        <th><i class="fas fa-clock"></i> Cuando</th>
        <th>User</th>
        <th><i class="fas fa-tags"></i> Tags</th>
        <th><i class="fas fa-users"></i> Sectores</th>
        <th><i class="fas fa-spinner"></i> Estado</th>
        <th><i class="fas fa-heart"></i> Likes</th>
    </tr>
    </thead>
    <tbody>
    {% for idea in ideas %}
        <tr>
            <td>
                <a href="{{ path('idea_show', {'id': idea.id}) }}">{{ idea.name | capitalize}}</a>
            </td>
            <td>
                {{ idea.publishedAt ? idea.publishedAt | date_time_ago : 'ahora' }}
            </td>
            <td>
                <button type="button" class="btn" data-toggle="tooltip" data-placement="top" title="{{ idea.anonymous ? 'Anónimo': idea.owner.name }}">
                    <i class="fas fa-user"></i>
                </button>
            </td>
            <td>
                {% for tag in idea.tags %}
                    {{ include('components/tag.html.twig') }}
                {% endfor %}
            </td>
            <td>
                {% for sector in idea.sectors %}
                    {{ include('components/sector.html.twig') }}
                {% endfor %}
            </td>
            <td>
                {% include 'components/status.html.twig' with {'status': idea.status } %}
            </td>
            <td>
                {% include 'components/liker.html.twig' %}
            </td>
        </tr>
    {% else %}
        <tr>
            <td colspan="5">no records found</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

templates/components/liker.html.twig
<div class="d-flex flex-row justify-content-start align-items-center flex-row justify-content-start align-items-center">
    <a data-userid="{{ app.user.id }}" data-token="{{ csrf_token(app.user.id) }}" data-ideaid="{{ idea.id }}" class="btn btn-danger rounded-circle sendChangeLikeRequest mr-2">
        <i class="fas fa-heart"></i>
    </a>
    <a class="likes-counter" id="likes-counter-{{ idea.id }}"> {{ idea.likes|length }}</a>
</div>

templates/components/navbar.html.twig
<nav class="navbar navbar-expand-lg navbar-primary bg-light navbar-light indigo border-bottom w-100" id="nav">
    <a class="navbar-brand" href="{{ path('home') }}">
            <img class="img-logo" src="{{ asset('img/logo.png') }}" alt="logo">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
            aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav">
            <li class="nav-item {{ app.request.get('_route')|slice(0,4) == 'home' ? 'active' }}">
                <a class="nav-link" href="{{ path('home') }}">
                    <i class="fas fa-home"></i>
                    Home
                    <span class="sr-only">(current)</span>
                </a>
            </li>
            <li class="nav-item {{ app.request.get('_route')|slice(0,5) == 'idea_' and app.request.get('_route')|slice(0,11) != 'idea_status' ? 'active' }}">
                <a class="nav-link" href="{{ path('idea_index') }}">
                    <i class="fas fa-lightbulb"></i>
                    Ideas
                </a>
            </li>
            {% if is_granted('ROLE_TAG_SHOW') %}
                <li class="nav-item {{ app.request.get('_route')|slice(0,4) == 'tag_' ? 'active' }}">
                    <a class="nav-link" href="{{ path('tag_index') }}">
                        <i class="fas fa-tags"></i>
                        Tags
                    </a>
                </li>
            {% endif %}
            {% if is_granted('ROLE_USER_SHOW') %}
                <li class="nav-item {{ app.request.get('_route')|slice(0,5) == 'user_' ? 'active' }}">
                    <a class="nav-link" href="{{ path('user_index') }}">
                        <i class="fas fa-user-friends"></i>
                        Personas
                    </a>
                </li>
            {% endif %}
            {% if is_granted('ROLE_ANALYTIC') %}
                <li class="nav-item {{ app.request.get('_route')|slice(0,8) == 'analytic' ? 'active' }}">
                    <a class="nav-link" href="{{ path('analytic_index') }}">
                        <i class="fas fa-chart-pie"></i>
                        Analítica
                    </a>
                </li>
            {% endif %}
            {% if is_granted('ROLE_STATUS_FULL') %}
                <li class="nav-item {{ app.request.get('_route')|slice(0,11) == 'idea_status' ? 'active' }}">
                    <a class="nav-link" href="{{ path('idea_status_index') }}">
                        <i class="fas fa-spinner"></i>
                        Estados
                    </a>
                </li>
            {% endif %}
            {% if is_granted('ROLE_NOTE_SHOW') %}
                <li class="nav-item {{ app.request.get('_route')|slice(0,5) == 'note_' ? 'active' }}">
                    <a class="nav-link" href="{{ path('note_index') }}">
                        <i class="fas fa-star"></i>
                        Evaluaciones
                    </a>
                </li>
            {% endif %}
            {% if is_granted('ROLE_SECTOR_SHOW') %}
                <li class="nav-item {{ app.request.get('_route')|slice(0,7) == 'sector_' ? 'active' }}">
                    <a class="nav-link" href="{{ path('sector_index') }}">
                        <i class="fas fa-layer-group"></i>
                        Sectores
                    </a>
                </li>
            {% endif %}
        </ul>
        {% if app.user %}
            <div class="dropdown ml-auto">
                <button class="btn btn-outline-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-user ml-auto"></i>
                </button>
                <div class="dropdown-menu  dropdown-menu-lg-right" aria-labelledby="dropdownMenuButton">

                    <a href="#" class="dropdown-item">
                        <i class="fas fa-cog"></i>
                        My Account
                    </a>
                    <a href="{{ path('app_logout') }}" class="dropdown-item">
                        <i class="fas fa-sign-out-alt"></i>
                        Logout
                    </a>
                </div>
            </div>
        {% else %}
            <a href="{{ path('app_login') }}" class="login-link btn btn-primary ml-auto">
                <i class="fas fa-sign-in-alt"></i>
                Login
            </a>
        {% endif %}
    </div>
</nav>

templates/components/new_button.html.twig
<a class="btn btn-primary btn-grad my-4"
   href="{{ path }}">
    <i class="fas fa-plus-circle"></i>
    {{ text }}
</a>

templates/components/search.html.twig
<form class="form-inline my-4 mt-2">
    <input class="form-control w-75" type="search" placeholder="Buscar" aria-label="Search">
    <button class="btn btn-outline-light my-2 my-sm-0 w-25" type="submit"><i class="fas fa-search"></i></button>
</form>

templates/components/sector.html.twig
<a href="{{ path('idea_by_sector',{ 'sector':sector.id }  ) }}" class="btn btn-outline-primary rounded mb-1">{{ sector.name }}</a>

templates/components/sidebar.html.twig
<div class="col-3 bg-info sidebar">
    <div class="container">
        {% include 'components/search.html.twig' %}
        {% if sideBar is defined %}
            {% if sideBar.tags is defined %}
                {% include 'components/sidebar/tag_container.html.twig' %}
            {% endif %}
            {% if sideBar.sectors is defined %}
                <div class="widget sector-container bg-light mt-3 mh-25 overflow-auto p-2 rounded">
                    <h4><i class="fas fa-users"></i> Sectores</h4>
                    {% for sector in sideBar.sectors %}
                        {% include 'components/sector.html.twig' %}
                    {% endfor %}
                </div>
            {% endif %}
            {% if sideBar.states is defined %}
                <div class="widget tags-container bg-light mt-3 mh-45 overflow-auto p-2 rounded">
                    <h4><i class="fas fa-spinner"></i> Estados</h4>
                   <div class="status-container d-flex flex-column align-items-center">
                       {% for status in sideBar.states %}
                           {% include 'components/status.html.twig' with {'status': status, 'noname':'yes' } %}
                       {% endfor %}
                   </div>
                </div>
            {% endif %}
        {% endif %}
    </div>
</div>

templates/components/status.html.twig
{% if status is not defined %}
    {% set status=idea.status %}
{% endif %}
{% set changeIdeaStatus = is_granted('IDEA_STATUS',idea) %}
<div class="div d-inline">
    {% if changeIdeaStatus %}
        <a href="{{ path('idea_edit',{ id: idea.id }) }}" class="d-flex align-items-center justify-content-center">
    {% else %}
        <a href="{{ path('idea_by_status',{ status:status.id }) }}">
    {% endif %}
            <div class="d-inline-flex flex-column align-items-center">
                <div class="circles {{ classes | default('') }}">
                    {% set n=status.maxNumber %}
                    {% for i in 1..n %}
                        <div class="status-circle" style="background-color: {{ status.number >= i ? status.color : '' }}"></div>
                    {% endfor %}
                </div>
                <h5 class="text-center">{{ status.name }}</h5>
            </div>
            {% if changeIdeaStatus %}
                <i class="fas fa-pencil-alt ml-1"></i>
            {% endif %}
        </a>
</div>

templates/components/tag.html.twig
<a href="{{ path('idea_by_tag',{ 'tag':tag.id }  ) }}" class="btn btn-outline-info rounded-pill mb-1{{ class|default('') }}">{{ tag.name }}</a>