src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use DateTime;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity=Idea::class, mappedBy="owner")
     */
    private $ideas;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="user", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity=Like::class, mappedBy="user", orphanRemoval=true)
     */
    private $likes;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $last_request;

    /**
     * @ORM\ManyToMany(targetEntity=Sector::class, mappedBy="users")
     */
    private $sectors;

    /**
     * @ORM\Column(type="string", length=63, nullable=true)
     */
    private $name;

    /**
     * @ORM\OneToMany(targetEntity=Note::class, mappedBy="user", orphanRemoval=true)
     */
    private $notes;

    public function __construct()
    {
        $this->last_request = new DateTime();
        $this->ideas = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->likes = new ArrayCollection();
        $this->sectors = new ArrayCollection();
        $this->notes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        if ($this->name) {
            return $this->name;
        }
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection|Idea[]
     */
    public function getIdeas(): Collection
    {
        return $this->ideas;
    }

    public function addIdea(Idea $idea): self
    {
        if (!$this->ideas->contains($idea)) {
            $this->ideas[] = $idea;
            $idea->setOwner($this);
        }

        return $this;
    }

    public function removeIdea(Idea $idea): self
    {
        if ($this->ideas->removeElement($idea)) {
            // set the owning side to null (unless already changed)
            if ($idea->getOwner() === $this) {
                $idea->setOwner(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return (string) $this->getUsername();
    }

    /**
     * @param Idea|Comment $idea
     * @return bool
     */
    public function hasAuth($idea): bool
    {
        if ( method_exists($idea,'getOwner')) {
            return $idea->getOwner() === $this || in_array('ROLE_ADMIN',$this->getRoles(),true);
        }
        return $idea->getUser() === $this || in_array('ROLE_ADMIN',$this->getRoles(),true);
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Like[]
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(Like $like): self
    {
        if (!$this->likes->contains($like)) {
            $this->likes[] = $like;
            $like->setUser($this);
        }

        return $this;
    }

    public function removeLike(Like $like): self
    {
        if ($this->likes->removeElement($like)) {
            // set the owning side to null (unless already changed)
            if ($like->getUser() === $this) {
                $like->setUser(null);
            }
        }

        return $this;
    }

    public function getLastRequest(): ?DateTimeInterface
    {
        return $this->last_request;
    }

    public function setLastRequest(?DateTimeInterface $last_request): self
    {
        $this->last_request = $last_request;

        return $this;
    }

    /**
     * @return Collection|Sector[]
     */
    public function getSectors(): Collection
    {
        return $this->sectors;
    }

    public function addSector(Sector $sector): self
    {
        if (!$this->sectors->contains($sector)) {
            $this->sectors[] = $sector;
            $sector->addUser($this);
        }

        return $this;
    }

    public function removeSector(Sector $sector): self
    {
        if ($this->sectors->removeElement($sector)) {
            $sector->removeUser($this);
        }

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|Note[]
     */
    public function getNotes(): Collection
    {
        return $this->notes;
    }

    public function addNote(Note $note): self
    {
        if (!$this->notes->contains($note)) {
            $this->notes[] = $note;
            $note->setUser($this);
        }

        return $this;
    }

    public function removeNote(Note $note): self
    {
        if ($this->notes->removeElement($note)) {
            // set the owning side to null (unless already changed)
            if ($note->getUser() === $this) {
                $note->setUser(null);
            }
        }

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('email')
            ->add('roles',ChoiceType::class,[
                'expanded'=>true,
                'choices' => [
                    'Ver todas las ideas' => 'ROLE_VIEWER',
                    'Crear cualquier idea' => 'ROLE_IDEA_NEW',
                    'Evaluar cualquier idea' => 'ROLE_NOTE_NEW',
                    'Comentar ideas' => 'ROLE_COMMENT_NEW',
                    // TODO: cambiar estado de idea sin poder editarla toda
                    'Editar todos usuarios'=>'ROLE_USER_FULL',
                    'Editar todas tags'=>'ROLE_TAG_FULL',
                    'Editar todos estados de ideas'=>'ROLE_IDEA_EDIT',
                    'Editar todos comentarios'=>'ROLE_COMMENT_FULL',
                    'Editar todas evaluaciones'=>'ROLE_NOTE_FULL',
                    'Administrar todo'=>'ROLE_ADMIN'
                ],
                'required'=>true,
                'multiple'=>true
            ])
            ->add('plainPassword',PasswordType::class, [
                'mapped'=>false,
                'label'=>'contraseña'
            ])
           // ->add('last_request')
            ->add('name',null,[
                'label'=>'Nombre'
           ])
            ->add('sectors',null,[
                'expanded'=>true,
                'label'=>'Sectores'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\IdeaRepository;
use App\Repository\UserRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

/**
 * @Route("/user")
 */
class UserController extends AbstractController
{
    /**
     * @Route("/home", name="user_home", methods={"GET"})
     * @param UserRepository $userRepository
     * @param $ideaRepository
     * @return Response
     */
    public function home(UserRepository $userRepository, IdeaRepository $ideaRepository): Response
    {
        $ideas = $ideaRepository->findAllOfThisUser($this->getUser());
        return $this->render('user/home.html.twig',[
            'ideas'=>$ideas
        ]);
    }

    /**
     * @Route("/", name="user_index", methods={"GET"})
     * @Security("is_granted('ROLE_USER_SHOW')")
     * @param UserRepository $userRepository
     * @return Response
     */
    public function index(UserRepository $userRepository): Response
    {
        $users = $userRepository->findAllOrderByIdeas();
        return $this->render('user/index.html.twig', [
            'users' => $users,
        ]);
    }

    /**
     * @Route("/new", name="user_new", methods={"GET","POST"})
     * @Security("is_granted('ROLE_USER_NEW')")
     * @param Request $request
     * @return Response
     */
    public function new(Request $request, UserPasswordEncoderInterface $encoder): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user->setPassword( $encoder->encodePassword( $user, $form->get('plainPassword')->getData() ));
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('user_index');
        }

        return $this->render('user/new.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_show", methods={"GET"})
     * @Security("is_granted('ROLE_USER_SHOW')")
     */
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="user_edit", methods={"GET","POST"})
     * @Security("is_granted('ROLE_USER_EDIT')")
     * @param Request $request
     * @param User $user
     * @return Response
     */
    public function edit(Request $request, User $user): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('user_index');
        }

        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_delete", methods={"DELETE"})
     * @Security("is_granted('ROLE_USER_DELETE')")
     * @param Request $request
     * @param User $user
     * @return Response
     */
    public function delete(Request $request, User $user): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('user_index');
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Guardar') }}</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editar Usuario{% endblock %}

{% block body %}
    <div class="container bg-light mt-5 rounded">
        <h1>Editar Usuario</h1>

        {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

        <a href="{{ path('user_index') }}" class="text-white"><i class="fas fa-arrow-circle-left"></i> Volver al listado</a>

        {{ include('user/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/user/home.html.twig
{% extends 'base.html.twig' %}

{% block title %}Home{% endblock %}

{% block body %}
    <div class="container-fluid h-100">
        <div class="row">
            <div class="col-3 h-90vh widget d-flex flex-column align-items-center justify-content-around position-sticky sticky-top">
                <div class="d-flex flex-column align-items-center justify-content-between">
                    <img class="mw-50 rounded-circle" src="{{ asset('img/profile.png') }}" alt="">
                    <h1 class="text-white"> {{ app.user.name }}</h1>
                    <div class="bg-dark rounded p-2">
                        <h5><i class="fas fa-lightbulb"></i> Ideas: {{ app.user.ideas|length }}</h5>
                        <h5>Comentarios: {{ app.user.comments|length }}</h5>
                        <h5>Likes: {{ app.user.likes|length }}</h5>
                        <h5>Evaluaciones: {{ app.user.notes|length }}</h5>
                    </div>
                </div>
            </div>
            <div class="container col-9 bg-light widget p-0 m-0">
                <tbody class="p-0 m-0">
                    {{ include('components/ideas_list.html.twig') }}
                </tbody>
            </div>
        </div>
    </div>
{% endblock %}

templates/user/index.html.twig
{% extends 'base_with_menu.html.twig' %}

{% block title %}Users{% endblock %}

{% block body %}
    {% if is_granted('ROLE_USER_NEW') %}
        {% include 'components/new_button.html.twig' with { 'text': 'Nuevo Usuario!', 'path': path('user_new') } %}
    {% endif %}
    <h1 class="{{ class_title|default('') }} text-center">Listado de usuarios</h1>

    <table class="table {{ class_table| default('') }}">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Ideas</th>
                {% if is_granted('ROLE_ADMIN') %}
                    <th>Roles</th>
                {% endif %}
                <th>Ultima vez visto</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.username }}</td>
                <td>{{ user.ideas.count }}</td>
                {% if is_granted('ROLE_ADMIN') %}
                    <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
                {% endif %}
                <td>{{ user.lastRequest ? user.lastRequest | date_time_ago : 'ahora' }}</td>
                <td>
                    <a href="{{ path('user_show', {'id': user.id}) }}">Mostrar</a>
                    <a href="{{ path('user_edit', {'id': user.id}) }}">Editar</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Crear usuario{% endblock %}

{% block body %}
<div class="container bg-light mt-5 rounded">

<h1>Crear usuario</h1>

    {{ include('user/_form.html.twig') }}

    <a href="{{ path('user_index') }}" class="text-white"><i class="fas fa-arrow-circle-left"></i> Volver al listado</a>
</div>
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
    <h1>User</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ user.password }}</td>
            </tr>
            <tr>
                <th>Last_request</th>
                <td>{{ user.lastRequest ? user.lastRequest|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ user.name }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('user_index') }}">Volver al listado</a>

    <a href="{{ path('user_edit', {'id': user.id}) }}">Editar</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}